version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5051:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=librarydb
    volumes:
      - library_pg_data:/bitnami/postgresql

volumes:
  library_pg_data:
